### PR TITLE
Upload contact index

### LINKED ISSUE #335: upload the contact [information] of an identity to the index server
It should be possible to upload contact to the register server.

for new created identities
for already existing

### PR DESCRIPTION
**Pull request by nnice**
resolves #335  

* [ ] integrate dependency
* [ ] gui for uploading

depends on #387 and #183

### CODE REVIEW

**Comment by JoGir** [comment]
after https://github.com/Qabel/qabel-core/pull/592 is merged pls use IndexService

**Comment by JoGir** [comment]
Or use the current commit ref in my PR

**Comment by julianseeger** [comment]
>resolves #335
TODO: gui is missing add after depends

so it doesn't resolve #335 ;)

**Comment by nnice** [comment]
well, of course it doesn't resolve it in it's current state. after the gui is added its resolved.
thats why i wrote that there is a TODO and and dependencies, and the fancy WIP and dependent label :)

**Comment by julianseeger** [comment]
Yea sry, I was so excited about the new review features that I mixed up the PRs ;)

**Comment by julianseeger** [comment]
continued in #457

**Pull request closed without merging**
